## Pressure Layer Prep

**Score** = #_of_species_introduction_event / reference_point

**Reference point** = 10 introduction events (with no additional information, this is an arbitrary number set for now, as for BHI 1.0) 

```{r invasive spp setup, message = FALSE}
## root location of the raw data
source(here::here("R", "setup.R"))
source(here::here("R", "spatial.R"))

dir_A <- file.path(dirname(dir_prep), "bhi-data")
dir_B <- file.path(dirname(dir_prep), "bhi-data", "BHI 2.0")
dir_rawdata <- file.path(dir_B, "Pressure", "invasive_spp")

bhi_basin_lookup <- read_delim(file.path(dir_prep, "supplement", "lookup_tabs", "bhi_basin_country_lookup.csv"), delim = ";") %>% 
  rename(country = rgn_nam) 
```


```{r read in data}
country_score <- read_delim(file.path(dir_rawdata, "invasive_spp.csv"), delim = ";") %>% 
  mutate(ref_pt = 10, 
         score = min(1, num_invasive/ref_pt))

bhi_score <- full_join(country_score, bhi_basin_lookup, by = 'country') %>% 
  dplyr::select(rgn_id = BHI_ID, 
         pressure_score = score)

# Save pressure layer
write_csv(bhi_score, file.path(dir_layers, "sp_invasives_bhi2019.csv"))

```
