
### 2.1 Datasets with Sources {-}
<br/>

The data for the Biodiversity goal consists of 4 shapefiles downloaded from HELCOM Metadata catalogue, with status and metrics reported by HELCOM Assessment Units – HELCOM open sea sub-basins and coastal WFD water bodies.


#### 2.1.1 Habitats {-}

**Integrated biodiversity status assessment - Benthic Habitats**

<!-- dataset save location BHI_share/BHI 2.0/Goals/BD/helcom_integrated_assessments -->
Source: [HELCOM Metadata catalogue: ](http://metadata.helcom.fi/geonetwork/srv/eng/catalog.search#/metadata/478d52dd-08b7-4777-b879-8806b1188b27) 

Downloaded 9 September 2020 by Ellie Campbell.

For more information about the dataset and indicators see the [State of the Baltic Sea webpage on Benthic Habitats](http://stateofthebalticsea.helcom.fi/biodiversity-and-its-status/benthic-habitats/).


**Integrated biodiversity status assessment - Pelagic Habitats**

<!-- dataset save location BHI_share/BHI 2.0/Goals/BD/helcom_integrated_assessments -->
Source: [HELCOM Metadata catalogue: ](http://metadata.helcom.fi/geonetwork/srv/eng/catalog.search#/metadata/821b33a7-35b3-489c-93ab-9ef8f4422f2a)

Downloaded 9 September 2020 by Ellie Campbell.

For more information about the dataset and indicators see the [State of the Baltic Sea webpage on Pelagic Habitats](http://stateofthebalticsea.helcom.fi/biodiversity-and-its-status/pelagic-habitats/).


#### 2.1.2 Species Groups {-}


**Integrated biodiversity status assessment - Fish**

<!-- dataset save location BHI_share/BHI 2.0/Goals/BD/helcom_integrated_assessments -->
Source: [HELCOM Metadata catalogue: ](http://metadata.helcom.fi/geonetwork/srv/eng/catalog.search#/metadata/ee20ad8b-c826-4561-b63a-bf203bb481b9) 

Downloaded 9 September 2020 by Ellie Campbell.

For more information about the dataset and indicators see the [State of the Baltic Sea webpage on Fish](http://stateofthebalticsea.helcom.fi/biodiversity-and-its-status/fish/).


**Integrated biodiversity status assessment - Seals**

<!-- dataset save location BHI_share/BHI 2.0/Goals/BD/helcom_integrated_assessments -->
Source: [HELCOM Metadata catalogue: ](http://metadata.helcom.fi/geonetwork/srv/eng/catalog.search#/metadata/c1662d7b-f63a-48cc-96f6-3072d328ae56)

Downloaded 9 September 2020 by Ellie Campbell.

For more information about the dataset and indicators see the [State of the Baltic Sea webpage on Marine Mammals (Seals)](http://stateofthebalticsea.helcom.fi/biodiversity-and-its-status/marine-mammals/).


**Abundance of waterbirds in the breeding season, 2018**

<!-- dataset save location BHI_share/BHI 2.0/Goals/BD/helcom_integrated_assessments -->
Source: [HELCOM Metadata catalogue: ](http://metadata.helcom.fi/geonetwork/srv/eng/catalog.search#/metadata/67d2f5e9-7f56-4ef0-87f0-a036528c56b9). The metadata catalogue and Map Viewer have pages/layers titled by bird groups (wading, surface, pelagic, benthic, grazing feeders), but the data linked on each of the metadata catalogue pages seem to be the same shapefile with all these groups included.

Downloaded 10 September 2020 by Ellie Campbell.

For more information about the dataset and indicators see the [State of the Baltic Sea webpage on Waterbirds](http://stateofthebalticsea.helcom.fi/biodiversity-and-its-status/waterbirds/).


**Abundance of waterbirds in the wintering season, 2018**

<!-- dataset save location BHI_share/BHI 2.0/Goals/BD/helcom_integrated_assessments -->
Source: [HELCOM Metadata catalogue: ](http://metadata.helcom.fi/geonetwork/srv/eng/catalog.search#/metadata/cf3f0772-acd1-4674-8c78-44ea5abbe5f1). The metadata catalogue and Map Viewer have pages/layers titled by bird groups (wading, surface, pelagic, benthic, grazing feeders), but the data linked on each of the metadata catalogue pages seem to be the same shapefile with all these groups included.

For more information about the dataset and indicators see the [State of the Baltic Sea webpage on Waterbirds](http://stateofthebalticsea.helcom.fi/biodiversity-and-its-status/waterbirds/).

Downloaded 10 September 2020 by Ellie Campbell.


<br>

