### Goal Description

The Nutrient sub-goal of the Clean Water goal captures the degree to which local waters are affected by eutrophication. For the BHI four eutrophication indicators were included: 

-	winter (December-February) dissolved inorganic nitrogen (DIN) 
-	dissolved inorganic phosphorus (DIP) concentrations in the surface layer (0 - 10 m depth)
-	summer (June-September) chlorophyll a concentration in the surface layer (0 - 10 m depth) 
-	summer (June-September) Secchi depth, 
-	hypoxic area below the halocline. 

The first three indicators are HELCOM core indicators (Baltic Sea Environmental Proceedings No 143). Hypoxic area is taken from Carstensen et al 2014. 


### Model & Data

The geometric mean of the status of all five indicators have been calculated for Bornholm Basin, Western Gotland Basin, Eastern Gotland Basin, Northern Baltic Proper and Gulf of Finland. For the other basins only four indicators (without hypoxic area) have been used to calculate the eutrophication status.

-	Mean Summer Secchi depth (June-September) data from ICES database.
-	Hypoxic area data published by Carstensen et al. 2014. Deep water anoxia are defined as O2 level <2 mg⋅L−1. It represents the long-term effects of human activities on nutrient levels and water quality. We used deep water anoxia only for the following basins: Bornholm Basin, Western Gotland Basin, Eastern Gotland Basin, Northern Baltic Proper and Gulf of Finland.
-	Winter (DIN), (DIP), and summer chorophyll a data have been downloaded from the Baltic Nest Institute database (DAS and NEST) with help from Miguel Rodriguez Medina.

### Reference points

_Secchi depth_ reference points are set based on the results obtained in the TARGREV project (HELCOM 2013a), taking advantage of the work carried out during the EUTRO PRO project (HELCOM 2009) and national work for WFD. The final targets were set through an expert evaluation process done by the intersessional activity on development of core eutrophication indicators (HELCOM CORE EUTRO) and the targets were adopted by the HELCOM Heads of Delegations. More information: 

-	Approaches and methods for eutrophication target setting in the Baltic Sea region
-	Fleming-Lehtinen and Laamanen. 2012. Long-term changes in Secchi depth and the role of phytoplankton in explaining light attenuation in the Baltic Sea. Estuarine, Coastal, and Shelf Science 102-103:1-10
-	EUTRO-OPER. Included on this page is a link to the Eutrophication Assessment Manual

The _hypoxic_ area reference point is set to be the hypoxic area of each basin in 1906.

Reference points for the _winter (DIN), (DIP), and summer chlorophyll_ a have been assessed from the Baltic Sea Environmental Proceedings No 143.


### Considerations for *BHI 2.0*

### Other information

*external advisors/goalkeepers: Christoph Humborg*
