
### 2.1 Datasets with Sources {-}
<br/>

#### 2.1.1 Oxygen Data {-}


Data are the same as were used for the oxygen debt clean water indicator. More about the data sources and data preparation can be found in the [Clean Water subgoal Eutrophication](https://github.com/OHI-Science/bhi-prep/blob/master/data/CW/eutrophication/v2019/eut_data.rmd) and the [BHI repository forked from ICES tools HEAT assessment tool repository](https://github.com/OHI-Baltic/HEAT).

<br>

**ICES Oxygen Data**
<!-- dataset save location BHI_share/BHI 2.0/Goals/CW/EUT/OxygenDebt_ICES -->

Data downloaded from the [ICES database](https://ocean.ices.dk/HydChem/HydChem.aspx?plot=yes). Each dataset has been extracted by country and Denmark split into five (5) because too big otherwise.


**ICES CTD Data**
<!-- dataset save location BHI_share/BHI 2.0/Goals/CW/EUT/OxygenDebt_ICES -->

Data downloaded from the [ICES database](https://ocean.ices.dk/HydChem/HydChem.aspx?plot=yes). Each dataset has been extracted by country, Denmark split into three (3) and Germany into five (5) because too big otherewise. No CTD found for Lithuania.


**SMHI CTD Data**
<!-- dataset save location BHI_share/BHI 2.0/Goals/CW/EUT/OxygenDebt_ICES -->

Data downloaded from the [SMHI Database](https://sharkweb.smhi.se/), Physical and Chemical parameters,  CTD Profiles.

<br>
