---
title: "Wild-Caught Fisheries - Food Provision Subgoal data prep"
output:
  github_document:
    toc: true
    toc_depth: 3
params: 
    datasource: csv
---

```{r Preamble}
loc <- file.path(here::here(), "prep", "FIS")

source(file.path(here::here(), "R", "setup.R"))
knitr::opts_chunk$set(message = FALSE, warning = FALSE, results = "hide")

bkgd_path <- file.path(here::here(), "supplement", "goal_summaries", "FIS.Rmd")
data_path <- file.path(here::here(), "data", "FIS", version_year, "fis_np_data.rmd")
refs_path <- file.path(loc, "fis_references.Rmd")
```

## 1. Background

```{r Background, child = bkgd_path, results = "asis", echo = FALSE}
```

<br/>

## 2. Data

```{r Data, child = data_path, results = "asis", echo = FALSE}
```

<br/>

## 3. Prep: Wrangling & Derivations, Checks/Evaluation, Gapfilling

This section prepares data layers for FIS and NP at the same time, separating the fish stocks for each:

- FIS stocks: cod_2224, cod_2532, her_3a22, her_2532, her_riga, her_30
- NP  stocks: spr_2232

```{r read raw datasets, message = FALSE, warning = FALSE}
## root location of the raw data
dir_rawdata <- file.path(dir_B, "Goals", "FP", "FIS") # list.files(dir_rawdata)

## PCBs data from ICES
cod1raw <- read_csv(file.path(dir_rawdata, "cod_SDs22_24", "cod_SDs22_24.csv"))
cod2raw <- read_csv(file.path(dir_rawdata, "cod_SDs24_32", "cod_SDs24_32.csv"))

herring1raw <- read_csv(file.path(dir_rawdata, "herring_SD_28.1", "herring_SD_28.1.csv"))
herring2raw <- read_csv(file.path(dir_rawdata, "herring_SDs20_24", "herring_SDs20_24.csv"))
herring3raw <- read_csv(file.path(dir_rawdata, "herring_SDs25_29_32", "herring_SDs25_29_32.csv"))
herring4raw <- read_csv(file.path(dir_rawdata, "herring_SDs30_31", "herring_SDs30_31.csv"))
```


```{r}

```


<br/>

## 4. Visualizing Data Layers

<br/>

## 5. References

```{r References, child = refs_path, results = "asis", echo = FALSE}
```