---
output:
  html_document:
    toc: true
    toc_float: true
---

[cw_coastalpopn_trend](https://github.com/OHI-Science/bhi/blob/master/baltic/layers/cw_coastalpopn_trend_gl2014.csv)\
*Units: trend score*\
*Category:*\
*Subcategory:*\
*Index Dimension: Status and Trend*\
*Goal Targets: CW*\
<br>

Coastal population, defined as the total population inland of 25 miles, extracted from Gridded Population of the World (GPW) Population Density Grid Future Estimates.
Data sources:
- Center for International Earth Science Information Network (CIESIN)/Columbia University

- CIESIN & CIAT (Center for International Earth Science Information Network (CIESIN)/Columbia University, & Centro Internacional de Agricultura Tropical (CIAT)) (2005). **Gridded Population of the World, Version 3 (GPWv3): Population Density Grid, Future Estimates**. Palisades, NY. [NASA Socioeconomic Data and Applications Center (SEDAC)](http://sedac.ciesin.columbia.edu/data/set/gpw-v3-population-density-future-estimates)\
*Will add more text here as the layers are prepared for the BHI2.0*

See [**CW prep documents**](https://github.com/OHI-Science/bhi-1.0-archive/blob/draft/baltic2015/prep/CW/cw_prep.md) for more information about data and methods.

<br>

