---
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
source(file.path(here::here(), "R", "setup.R"))
short_layer_web <- file.path(bhiprep_gh_raw, "master", "ref", "layer_summaries") # bhiprep_gh_raw defined in setup.R
```

## Directive 2008/56/Ec Of The European Parliament And Of The Council Of 17 June 2008 Establishing A Framework For Community Action In The Field Of Marine Environmental Policy

[res_reg_msfd](https://github.com/OHI-Science/bhi/blob/master/baltic/layers/res_reg_msfd_bhi2015.csv.csv)
*Units: resilience score*
*Category:*
*Subcategory:*
*Index Dimension: Resilience*
*Goal Targets: resilience*

<br>

```{r, echo = FALSE, results = "hide"}
tmp <- tempfile(fileext = "Rmd")
on.exit(unlink(tmp))
download.file(file.path(short_layer_web, "res_reg_msfd.Rmd"), tmp) 
```

```{r, child = tmp, echo = FALSE, results = "asis"} 
``` 

See [**THISGOAL**](link/to/dataprep/or/something) for more information about data and methods.

<br>

---- 
