---
title: "Mariculture - Food Provision Subgoal data prep"
output:
  github_document:
    toc: true
    toc_depth: 4
params: 
    datasource: csv
---

```{r Preamble}
loc <- file.path(here::here(), "prep", "MAR")

source(file.path(here::here(), "R", "setup.R"))
source(file.path(here::here(), "R", "prep.R"))
knitr::opts_chunk$set(message = FALSE, warning = FALSE, results = "hide")

bkgd_path <- file.path(here::here(), "supplement", "goal_summaries", "MAR.Rmd")
data_path <- file.path(here::here(), "data", "MAR", v2019, "mar_data.rmd")
refs_path <- file.path(loc, "mar_references.Rmd")
```

## 1. Background

```{r Background, child = bkgd_path, results = "asis", echo = FALSE}
```

<br/>

<!-- ## 2. Data --- header in the child  document -->
```{r Data, child = data_path, results = "asis", echo = FALSE}
```

<br/>

## 3. Prep: Wrangling & Derivations, Checks/Evaluation, Gapfilling

### 3.1 Reorganizing/wrangling

This section prepares production and spatial data for MAR. 

<br>

#### 3.1.1 Load datasets

<!-- Swedish aquaculture facilities --> 

```{r}
library(sf)
shape1 <- read_sf(dsn = ".", layer = "AF_Vattenbruk")

plot(shape1)
```

<!-- Finfish mariculture - HELCOM --> 
```{r}
library(sf)
shape2 <- read_sf(dsn = ".", layer = "Finfish_mariculture") # OR
getwd()
setwd(dir = "/Volumes/BHI_share/BHI 2.0/Goals/FP/MAR")
finfish_mariculture <- st_read(
  "Finfish_mariculture/Finfish_mariculture.shp")
st_geometry_type(finfish_mariculture) 

ggplot() +
  geom_sf(data = finfish_mariculture, size = 3, color = "black", fill = "cyan1") +
  ggtitle("Finfish Mariculture") +
  coord_sf()

plot(shape2)

```

## 4. Visualizing Data Layers

<br/>

## 5. References

```{r References, child = refs_path, results = "asis", echo = FALSE}
```
