### 1.1 Goal Description {-}

This goal captures the biodiversity status of the Baltic Sea ecosystems and intactness of broad, encompassing marine habitats/zones.

### 1.2 Model & Data {-}

This goal consists of five components: 
- benthic habitats
- pelagic habitats
- fish
- mammals (seals)
- seabirds

It has been evaluated using the biological quality ratios and seabird abundance, derived in the integrated biodiversity assessments from HELCOM (the HELCOM assessment tool: https://github.com/NIVA-Denmark/BalticBOOST). 
These are based on core indicators for key species and species groups, including abundance, distribution, productivity, physiological and demographic characteristics. 

Statuses of these five biodiversity components are aggregated first within each component, combining coastal area values with area-weighted averages, then combining the values for coastal and offshore areas of each BHI region with equal weight. 
A single biodiversity status score per region is calculated as geometric mean of the five components. 
More detailed information on the indicators and the biodiversity assessment can be found at HELCOM (http://stateofthebalticsea.helcom.fi/biodiversity-and-its-status/).

### 1.3 Reference points {-}

For the seabirds, the HELCOM core indicator threshold of 0.75 abundance, decided by HELCOM, was used as good status (corresponding to a status score of 100 in BHI). 
For the other four components (benthic habitats, pelagic habitats, fish, and mammals), a biological quality ratio (BQR) of 0.6 was developed by HELCOM with the aim to represent good status and was used as here as the target.

### 1.4 Other information {-}

External advisors/goalkeepers: Andrea Belgrano and Henn Ojaveer