### 1.1 Goal Description {-}

The Economies goal captures the economic value associated with marine industries, using revenue from marine sectors. Currently, it is composed of a single component: revenue (Gross Value Added). Gross value added (GVA) is defined as the value of output less the value of intermediate consumption. It is used to measure the output or contribution of a particular sector.

Ideally, the economic sub-goal would also incorporate information on the sustainability of the different marine sectors. 


### 1.2 Model & Data {-}

#### 1.2.1 Data {-}

Data for each country were downloaded from [The EU Blue Economy Report. 2020.](https://ec.europa.eu/maritimeaffairs/sites/maritimeaffairs/files/2020_06_blueeconomy-2020-ld_final.pdf), which provided 2009 and 2018 marine sector-specific revenue data (GVA) among other metrics, in the country-specific Appendices. The report also identified the potential for Blue Growth in each of the EU Member States (MS) of the Baltic Sea Region (BSR) as well as at sea-basin level. 

(Due to a lack of data, Russian regions (19, 22, 33) have NA scores for this subgoal.)


#### 1.2.2 Status Model {-}

Because the Blue Economy Report 2020 contains GVA values only for 2009 and 2018, the actual annual growth rates are not known and instead a constant annual growth rate (AGR) across the 9 years is estimated using the formula:

$$AGR = \Bigg(\frac{FinalValue}{BeginningValue}\Bigg)^{\Big(1/numYears\Big)} - 1$$

Thus, all years between 2009 and 2018 will have the same status and trend values within a given country.

The goal model compares the estimated annual growth rate per sector to the target (1.5% between 2010 and 2020, as envisioned in the Report), calculating status first per sector. The overall status is then calculated as the average of the sector-statuses, weighted by relative contribution of the sectors to the country's total marine-related economic revenue.

$$Status = \sum_{Sectors}{\big((SectorRevenue/TotalRevenue) \cdot SectorStatus}\big)$$
  
$$SectorStatus = \begin{cases} 
      0 &  \hspace{10pt} SectorAGR \leq -1.5 \\
      100/3 \hspace{2pt}\cdot \hspace{2pt} SectorAGR \hspace{3pt} + \hspace{3pt} 50 & \hspace{10pt}-1.5\leq SectorAGR \leq 1.5 \\
      100 & \hspace{10pt} 1.5\leq SectorAGR
   \end{cases}
$$


#### 1.2.3 Trend Model {-}

Trend of this goal is the weighted average of the growth rates of each sector by their relative contribution to the total revenue, where the sector growth rates are the annual growth rates (AGR) estimated from 2009 and 2018 GVA data. 

$$Trend = \sum_{Sectors}{\big((SectorRevenue/TotalRevenue) \cdot SectorAGR}\big)$$


### 1.3 Reference points {-}

As reference points we used a 1.5% annual growth between 2010 and 2020, as envisioned in the Blue Growth Report. 


### 1.4 Other information {-}

External advisors/goalkeepers: Wilfried Rickels.

