### 1.1 Goal Description {-}

The Mariculture sub-goal describes a country's ability to maximize the sustainable yield of farmed fish in the ocean for human consumption. 

### 1.2 Model & Data {-}

Sustainable mariculture represents a good supplementary opportunity that can support food provisioning needs, especially when considering not compromising the water quality in the farmed area and not relying on wild populations to feed or replenish the cultivated species. However, assessing the sustainable production of farmed fish can be difficult, as information is limited (location of the fish farms, species produced, nutrient and antibiotic release from these farms). Overall, in terms of total fish production, mariculture is at the moment not a large industry in the Baltic Sea, and dominated by rainbow trout production, which was included using available national data.

Despite the production of rainbow trouts in some Baltic countries (Denmark, Germany, Sweden and Finland), there is currently very limited data on nutrient discharge, and therefore the Mariculture sub-goal was not assessed and will not contribute to the overall Food Provision goal score.
 
### 1.3 Reference points {-}

The maximum nutrient discharge for both phosphorus (P) and nitrogen (N) could be used as target for this sub-goal, if information is available. The [HELCOM Recommendation](http://www.helcom.fi/Recommendations/Rec%2025-4.pdf), provides a management target that existing and new marine fish farms should not exceed the annual average of 7g of P (total-P) and 50g of N (total-N) per 1kg fish (living weight) produced.

### 1.4 Other information {-}

Data for `BHI1.0` were compiled primarily by [Ginnette Flores Carmenate](https://bioenv.gu.se/digitalAssets/1575/1575339_flores-carmenate.pdf) as part of a Masters thesis. Data sources and aggregation approaches were slightly revised for `BHI2.0`. See data prep methods for more details.
