### 1.1 Goal Description {-}

Tourism in coastal areas is a major component of thriving coastal communities and a measure of how much people value ocean systems, i.e. by traveling to coastal and ocean areas. This goal is not about the revenue or livelihoods that are generated by tourism and recreation (that is captured in the livelihoods and economiess goal) but instead captures the value that people have for experiencing and enjoying coastal areas. A score of 100 means a region utilizes its full recreational potential without harming the ecosystem. 

In the BHI, we used revenue data (gross value added of coastal tourism activities) from the EU Study on Blue Growth, as well as Eurostat data (nights spent at tourist accommodation establishments by coastal and non-coastal area) to assess the status of Tourism. Economic activities under the Coastal tourism sector, Accommodation and Transport, were included. No sustainability measure of coastal tourism on the Baltic Sea scale was found, and thus this dimension was not included in the BHI2.0. 


### 1.2 Model & Data {-}

Data for each country were downloaded from the [EU-Study on Blue Growth](https://webgate.ec.europa.eu/maritimeforum/node/3550), Maritime Policy and the EU Strategy for the Baltic Sea Region” identified the potential for Blue Growth in each of the EU Member States (MS) of the Baltic Sea Region (BSR) and at sea basin level. The tourism model also incorporates the nights of stay in accommodations in coastal regions, which used Eurostat dataset on [nights spent at tourist accommodation establishments by coastal and non-coastal area](http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=tour_occ_nin2c&lang=en).

The status is the ratio of coastal tourism revenue relative to the coastal accommodations per area, scaled by the reference point.


### 1.3 Reference points {-}

We use as the reference point, in order to scale the ratio values between zero and one, the highest ratio across all countries in a ten year timeframe. The lowest score is fixed as the lower end point.


### 1.4 Other information {-}
