
## 2. Data

```{r Preamble, echo = FALSE, include = FALSE, error = FALSE}
source(here::here(), "R", "data.R")
source(here::here(), "R", "setup.R")
```


### 2.1 Datasets with Sources
<br/>

**Secchi Depth, ICES**
<!-- dataset save location BHI_share/BHI 2.0/Goals/CW/EUT/ -->
```{r echo = FALSE, results = "asis"}
tab <- t(data.frame(
  c("Dataset set:", "Oceanographic (per Parameter)"), 
  c("Parameter:", "secchi depth (Download)")))

colnames(tab) <- c("Option", "Specification")
rownames(tab) <- NULL

knitr::kable(tab, caption = "Source: [ICES data portal](http://ecosystemdata.ices.dk/inventory/Index.aspx?) <br/> Requested 23 May 2019 by Ellie Campbell; must request all records as web download limited to max 10000 records per layer")
```
<br/>

**Secchi Depth, SMHI**  
<!-- dataset save location BHI_share/BHI 2.0/Goals/CW/EUT/SecchiDepth_SMHI -->
```{r echo = FALSE, results = "asis"}
tab <- t(data.frame(
  c("Datatype:", "Physical and Chemical"), 
  c("Parameter:", "secchi depth"),
  c("Months:", "All"),
  c("Years:", "1893-2019 (all listed; though goes back only to 1967 in downloaded dataset)"),
  c("Decimal/fält-avgränsare (decimal/delimiter):", "punkt/semikolon (period/semicolon)"),
  c("Teckenkodning:", "UTF-8"),
  c("Rubrikrad:", "Englelska (English)")))

colnames(tab) <- c("Option", "Specification")
rownames(tab) <- NULL

knitr::kable(tab, caption = "Source: [SMHI Shark database](http://www.smhi.se/klimatdata/oceanografi/havsmiljodata/marina-miljoovervakningsdata) <br/> Downloaded 22 April 2019 by Ellie Campbell")
```
<br/>

**Chlorophyll A and Nutrients, Baltic Nest**
<!-- dataset save location BHI_share/BHI 2.0/Goals/CW/EUT/NestData/nestdata_nutrients_chlora.csv -->
```{r echo = FALSE, results = "asis"}
tab <- t(data.frame(
  c("Latitude/Longitude Begin/End:", "Baltic Sea"), 
  c("Dates Begin/End:", "Jan 1, 2005 to Dec 31, 2019"), 
  c("Parameters:", "PO4P, TOTP, SIO4, NO3N, NO2N, NO23N, NH4N, TOTN, CHL")))

colnames(tab) <- c("Option", "Specification")
rownames(tab) <- NULL

knitr::kable(tab, caption = "Source: [Baltic Nest database](http://nest.su.se/dataPortal/getStations) <br/> Downloaded 28 February 2020 by Ellie Campbell. See data.R/get_nest_data function for more detailed info.")
```

```{r using get_nest_data function to download data, eval = FALSE}
get_nest_data(date_range = c(20050101, 20191231), months = c(11, 12, 1, 2, 3)) %>% 
    readr::write_csv(file.path(dir_B, "Goals", "EUT", "NestData", "nestdata_nutrients_chlora.csv"))
```


### 2.2 Centralization & Normalization
<br/>

```{r}
```



### 2.3 Initial Data Exploration

#### 2.3.1 Compare versus Previous Years Data

#### 2.3.2 Timeseries Plots

#### 2.3.3 Map
